title: Debdeep Bhattacharya     
description: false
#description: Personal Webpage
is_user_page: true 
show_navigation: true
logo: content/pic.jpg
show_downloads: false 
google_analytics: UA-90023312-2
theme: jekyll-theme-minimal
repository: debdeepbh/debdeepbh.github.io

collections:
        blog:
                output: true

defaults:
  - scope:
      path: ""
      type: "blog"
    values:
      layout: blog
      comment: true
